[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "interfaces/=src/interfaces/"
]

# Test configuration
fuzz = { runs = 1000 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
